import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { parseConfig } from '../src/config.ts';
import { redactSensitive, taskContext } from '../src/context.ts';
import { workerDiagnostic } from '../src/diagnostics.ts';
import { assertSafeContent, safeFile, snapshot } from '../src/evidence.ts';

// Test list: real README unchanged in safeFile/snapshot; inline read-only prose;
// generated headers/comments; plural bearer prose; real/mixed credentials.
const config = parseConfig({});

test('content policy distinguishes inline read-only prose from generated headers', () => {
  assert.doesNotThrow(() => assertSafeContent('Common `do not edit/change/write` forms are recognized.', config));
  for (const marker of [
    'DO NOT EDIT', '  Do Not Edit! Created by a tool.\r\n', '\uFEFFDO NOT EDIT',
    '// DO NOT EDIT: generated file', '/* do not edit */', ' * DO NOT EDIT',
    '<!-- DO NOT EDIT -->', '# DO NOT EDIT', '-- DO NOT EDIT', '; DO NOT EDIT',
    '**DO NOT EDIT**', '## Do not edit this file', '//\tDo\tnot\tedit',
    '// auto-generated', 'Auto generated documentation', 'AUTOGENERATED',
    '<!-- generated -->', '<!--\tGenerated by a tool -->',
  ]) assert.throws(() => assertSafeContent(`Preamble\n${marker}\nBody`, config), /generated or sensitive content refused/, marker);
});

test('content policy refuses conventional generated warning variations', () => {
  for (const marker of [
    '// Code generated by a tool. DO NOT EDIT.', '/* WARNING: DO NOT EDIT */',
    '/*! DO NOT EDIT */', 'WARNING: DO NOT EDIT', '<!-- This file is generated. Do not edit. -->',
    '// This file is maintained by a tool; do not edit it.',
  ]) assert.throws(() => assertSafeContent(marker, config), /generated or sensitive content refused/, marker);
});

test('content policy preserves plural bearer prose but refuses credential values and mixed lines', () => {
  for (const prose of [
    'Common credentials, bearer tokens and private keys are redacted from prose.',
    'The bearer tokens are sensitive.',
  ]) {
    assert.equal(redactSensitive(prose), prose);
    assert.doesNotThrow(() => assertSafeContent(prose, config));
    assert.equal(taskContext([{type: 'message', id: 'user', message: {role: 'user', content: prose}}], config).entries[0].text, prose);
    assert.ok(workerDiagnostic('error', 'fixture/model', 1, prose).includes(prose));
  }
  for (const sensitive of [
    'Authorization: Bearer abc.def_123-+/=', 'proxy-authorization: bearer x',
    'The request used Bearer arbitrary-value.', 'Use bearer a for this request.',
    'Authorization: Bearer tokens', 'authorization: bearer tokens are sensitive',
    'auth = bearer tokens and private keys', '"bearer tokens are sensitive"',
    'bearer tokens', 'Bearer tokens are sensitive', 'bearer tokens123 are sensitive',
    'bearer tokens and private keys; Authorization: Bearer real-value',
    'bearer tokens are sensitive; use bearer real-value',
    'bearer tokens are sensitive\nBearer real-value',
    'bearer tokens are sensitive; password=another-value',
    'bearer tokens are sensitive; ghp_123456789abcdef',
  ]) {
    assert.notEqual(redactSensitive(sensitive), sensitive, sensitive);
    assert.throws(() => assertSafeContent(sensitive, config), /generated or sensitive content refused/, sensitive);
    assert.ok(workerDiagnostic('error', 'fixture/model', 1, sensitive).includes('[REDACTED SENSITIVE LINE]'), sensitive);
  }
});

test('content policy admits the real Clio README as exact file and snapshot evidence', async () => {
  const root = fileURLToPath(new URL('../', import.meta.url));
  const text = await readFile(new URL('../README.md', import.meta.url), 'utf8');
  assert.match(text, /do not edit\/change\/write/);
  assert.match(text, /bearer tokens and private keys/);
  const file = await safeFile(root, 'README.md', config, true);
  assert.equal(file.text, text);
  assert.equal(file.doc, true);
  const files = await snapshot(root, ['src/context.ts'], config);
  assert.equal(files.find(f => f.path === 'README.md')?.text, text);
});
